language: ruby
sudo: false
rvm:
  - "2.3.0"
services:
  - postgresql
before_script:
  - psql -c 'create database plantindoor_ci_test;' -U postgres
script: bundle exec rails spec
notifications:
  email:
    on_failure: change