language: ruby
sudo: false
rvm:
  - "2.3.1"
before_script:
  - "mysql -e 'create database travis_test;'"
  - "cp ./config/database.travis.yml ./config/database.yml"
script: bundle exec rails spec
notifications:
  email:
    on_success: change
    on_failure: change